# Generated by Django 3.2.10 on 2021-12-20 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('speciality', models.CharField(max_length=20)),
                ('door', models.CharField(max_length=5)),
                ('equipment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('adress', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 20, 21, 32, 13, 887947))),
                ('patient', models.CharField(max_length=300)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
