# Generated by Django 3.2.10 on 2021-12-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_docs_patient_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
