# Generated by Django 3.2.10 on 2021-12-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_visits_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
