# Generated by Django 3.2.10 on 2021-12-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_visits_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
